spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dornach
      client:
        registration:
          shipment-service:
            provider: keycloak
            client-id: order-service-client
            client-secret: ${ORDER_SERVICE_CLIENT_SECRET:order-service-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/dornach/protocol/openid-connect/token

server:
  port: 8083

shipment:
  service:
    url: http://localhost:8082

user:
  service:
    url: http://localhost:8081

app:
  sqs:
    order-events-queue: order-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0  # Sample all requests for demo
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.dornach: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

resilience4j:
  retry:
    instances:
      shipmentService:
        maxAttempts: 3
        waitDuration: 500ms
      userService:
        maxAttempts: 3
        waitDuration: 500ms
  timelimiter:
    instances:
      shipmentService:
        timeoutDuration: 2s
      userService:
        timeoutDuration: 2s

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    aws:
      sqs:
        endpoint: http://localstack:4566
  datasource:
    url: jdbc:postgresql://postgres:5432/dornach
    driver-class-name: org.postgresql.Driver
    username: dornach
    password: dornach
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/dornach
          jwk-set-uri: http://keycloak:8080/realms/dornach/protocol/openid-connect/certs
      client:
        registration:
          shipment-service:
            provider: keycloak
            client-id: order-service-client
            client-secret: ${ORDER_SERVICE_CLIENT_SECRET:order-service-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/dornach/protocol/openid-connect/token

shipment:
  service:
    url: http://shipment-service:8082

user:
  service:
    url: http://user-service:8081

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
